import React, {useState} from 'react';
import {createRoot} from 'react-dom/client';
const colors={'At Risk':'#ef776b','Watch':'#efb64f','On Track':'#5bc9a9','Top Performer':'#3157d5','Slow Learner':'#9d8cf5','Insufficient Data':'#8791a5'};
const fmt=v=>v==null?'—':Number(v).toFixed(1);
const reasons={SCORE_BELOW_60:'Score below 60%',DECLINING_SCORE:'Declining score',LOW_ATTENDANCE:'Attendance below 75%',TOP_DECILE_SCORE:'Institutional top decile',EXEMPLARY_ATTENDANCE:'Attendance at least 90%',PERSISTENT_60_69:'Three terms between 60–69%',LIMITED_IMPROVEMENT:'Improvement of 0–1 point',ADEQUATE_ATTENDANCE:'Attendance at least 75%',NEGATIVE_MOMENTUM:'Score fell from the prior term',STABLE_OR_IMPROVING:'Stable or improving score',MISSING_MARKS:'Assessment evidence incomplete'};
function Panel({title,subtitle,children,action}){return <section className="card visual-panel"><div className="visual-heading"><div><h2>{title}</h2><p className="sub">{subtitle}</p></div>{action}</div>{children}</section>}
export function Dashboard({live,onStudent,onPage}){
  const [status,setStatus]=useState('All'),[metric,setMetric]=useState('score'),[search,setSearch]=useState(''),[sort,setSort]=useState('priority'),[explain,setExplain]=useState(false),[hover,setHover]=useState(null);
  const {summary:s,students:all}=live;
  const rows=all.filter(r=>status==='All'||r.status===status);
  const mean=k=>{const v=rows.filter(r=>r[k]!=null);return v.length?v.reduce((a,r)=>a+r[k],0)/v.length:null};
  const statuses=Object.entries(s.statuses).filter(([,n])=>n>0);
  const bands=[[0,60,'Below 60'],[60,70,'60–69'],[70,80,'70–79'],[80,90,'80–89'],[90,101,'90–100']].map(([lo,hi,label])=>({label,n:rows.filter(r=>r.current_average!=null&&r.current_average>=lo&&r.current_average<hi).length}));
  const classes=[...new Set(rows.map(r=>r.class_name))].map(name=>{const rs=rows.filter(r=>r.class_name===name),values=rs.filter(r=>r[metric==='score'?'current_average':'attendance']!=null);return {name,n:rs.length,value:values.length?values.reduce((a,r)=>a+r[metric==='score'?'current_average':'attendance'],0)/values.length:null}});
  const signals=Object.keys(reasons).map(k=>({k,n:rows.filter(r=>r.reason_codes?.includes(k)).length})).filter(x=>x.n&& !['STABLE_OR_IMPROVING','ADEQUATE_ATTENDANCE','EXEMPLARY_ATTENDANCE','TOP_DECILE_SCORE'].includes(x.k)).sort((a,b)=>b.n-a.n);
  const priority={'At Risk':0,'Insufficient Data':1,'Slow Learner':2,'Watch':3,'On Track':4,'Top Performer':5};
  const queue=rows.filter(r=>r.name.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>sort==='score'?(a.current_average??101)-(b.current_average??101):sort==='decline'?(a.trend_delta??101)-(b.trend_delta??101):priority[a.status]-priority[b.status]||a.id-b.id);
  let cumulative=0;
  function exportRows(){const lines=[['Student ID','Name','Class','Score','Attendance','Change','Status','Reasons'],...rows.map(r=>[r.id,r.name,r.class_name,r.current_average,r.attendance,r.trend_delta,r.status,(r.reason_codes||[]).join('; ')])];const csv=lines.map(row=>row.map(v=>'"'+(typeof v==='string'&&/^[=+\-@\t\r]/.test(v)?"'"+v:String(v??'')).replace(/"/g,'""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='student-review.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
  return <>
    <div className="insight-toolbar"><div className="live-note"><span className="live-dot"/> Database connected <small>Synthetic demo · {new Date(live.fetched_at).toLocaleTimeString()}</small></div><div className="actions"><button className="btn secondary" onClick={()=>setExplain(!explain)} aria-expanded={explain}>How flags work</button><button className="btn secondary" onClick={exportRows}>Download visible data ↓</button></div></div>
    {explain&&<div className="logic-panel"><h2>Detect → Explain → Support → Review</h2><p>The server compares scores with the immediately prior term, checks attendance, and checks three-term patterns. It returns the category and the evidence used. Teachers then arrange support and record outcomes.</p><div className="logic-steps"><div><b>01 · At Risk</b><p>Score below 60%, or declining score with attendance below 75%.</p></div><div><b>02 · Top Performer</b><p>Institutional top-decile score and attendance of at least 90%.</p></div><div><b>03 · Slow Learner</b><p>Three complete terms at 60–69%, improvement of 0–1 point, attendance at least 75%.</p></div><div><b>04 · Watch / On Track</b><p>A falling score goes to Watch; remaining complete records go to On Track. Missing marks stay separate.</p></div></div><p className="sub">Rules run in this order. Indicators require teacher review. Rule: {s.rule_version}.</p></div>}
    <div className="visual-kpis">{[
      ['Students in view',rows.length,'◎',()=>setStatus('All')],['Average score',fmt(mean('current_average'))+'%','↗',()=>document.getElementById('score-bands').scrollIntoView({behavior:'smooth'})],['Average attendance',fmt(mean('attendance'))+'%','◷',()=>document.getElementById('signal-map').scrollIntoView({behavior:'smooth'})],['At Risk',s.statuses['At Risk'],'△',()=>setStatus('At Risk')],['Slow Learner',s.statuses['Slow Learner'],'◈',()=>setStatus('Slow Learner')],['Students in support',s.students_in_support,'▦',()=>onPage('support')],['Pending submissions',s.pending_submissions,'▤',()=>onPage('assignments')],['Reports to generate',s.reports_pending,'▧',()=>onPage('reports')]
    ].map(([label,value,icon,action],i)=><button key={label} className={'card visual-kpi tone-'+i} onClick={action}><div className="kpi-label">{label}<span className="kpi-icon">{icon}</span></div><div className="kpi-value">{value}</div><small>{i<3?'Current chart selection':i<5?'Click to focus this group':'Open workflow'} ↗</small><div className="kpi-accent"/></button>)}</div>
    <div className="focus-bar"><b>Explore a student group</b><div className="status-tabs">{['All',...Object.keys(colors)].map(k=><button key={k} className={status===k?'selected':''} aria-pressed={status===k} onClick={()=>setStatus(k)}><i style={{background:colors[k]||'var(--ink)'}}/>{k}</button>)}</div><span className="sub">{rows.length} of {all.length} students · global slicers apply to every chart</span></div>
    <div className="visual-grid">
      <Panel title="Academic momentum" subtitle="Average score across complete assessments · current global filters"><div className="chart-legend"><span><i style={{background:'var(--blue)'}}/> Score %</span><span>Click a term to change the global filter</span></div><svg className="data-svg" viewBox="0 0 520 230" role="img" aria-label="Average score by term, 0 to 100 percent"><defs><linearGradient id="trend-fill" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#3157d5" stopOpacity=".25"/><stop offset="1" stopColor="#3157d5" stopOpacity="0"/></linearGradient></defs>{[0,25,50,75,100].map(v=><g key={v}><line x1="40" x2="495" y1={190-v*1.6} y2={190-v*1.6} className="grid-line"/><text x="7" y={194-v*1.6}>{v}%</text></g>)}{s.trend.every(t=>t.average_score!=null)&&s.trend.length>0&&<><path d={'M40 190 '+s.trend.map((t,i)=>`L${55+i*430/Math.max(1,s.trend.length-1)} ${190-t.average_score*1.6}`).join(' ')+` L${55+(s.trend.length-1)*430/Math.max(1,s.trend.length-1)} 190 Z`} fill="url(#trend-fill)"/><polyline points={s.trend.map((t,i)=>`${55+i*430/Math.max(1,s.trend.length-1)},${190-t.average_score*1.6}`).join(' ')} fill="none" stroke="var(--blue)" strokeWidth="3"/></>}{s.trend.map((t,i)=>{const x=55+i*430/Math.max(1,s.trend.length-1),y=190-(t.average_score??0)*1.6;return <g key={t.term_id}><text x={x} y="217" textAnchor="middle">Term {t.term_id}</text>{t.average_score!=null&&<g className="svg-control" role="button" tabIndex="0" aria-label={`Term ${t.term_id}, ${fmt(t.average_score)} percent`} onClick={()=>window.dispatchEvent(new CustomEvent('chart-term',{detail:t.term_id}))} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();window.dispatchEvent(new CustomEvent('chart-term',{detail:t.term_id}))}}}><circle cx={x} cy={y} r="13" fill="transparent"/><circle cx={x} cy={y} r="5" fill="var(--blue)"/><text x={x} y={y-13} textAnchor="middle" className="value-label">{fmt(t.average_score)}</text><title>{`Term ${t.term_id}: ${fmt(t.average_score)}%`}</title></g>}</g>})}</svg><p className="chart-foot">Group selection affects the charts below. This trend follows the global slicers.</p></Panel>
      <Panel title="Student status" subtitle="Click a segment or legend to focus the review queue"><div className="status-chart"><svg viewBox="0 0 200 200" className="ring-chart" role="img" aria-label="Student status distribution"><circle cx="100" cy="100" r="72" fill="none" stroke="var(--line)" strokeWidth="23"/>{statuses.map(([k,n])=>{const start=cumulative;cumulative+=n/Math.max(1,s.total_students)*452.39;return <circle key={k} cx="100" cy="100" r="72" fill="none" stroke={colors[k]} strokeWidth={status===k?29:23} strokeDasharray={`${n/Math.max(1,s.total_students)*452.39} 452.39`} strokeDashoffset={-start} transform="rotate(-90 100 100)" className="svg-control" role="button" tabIndex="0" aria-label={`${k}: ${n} students`} onClick={()=>setStatus(k)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setStatus(k)}}}><title>{`${k}: ${n} (${fmt(n/Math.max(1,s.total_students)*100)}%)`}</title></circle>})}<text x="100" y="98" textAnchor="middle" className="ring-number">{s.total_students}</text><text x="100" y="120" textAnchor="middle">students</text></svg><div className="ring-legend">{statuses.map(([k,n])=><button key={k} onClick={()=>setStatus(k)} aria-pressed={status===k}><i style={{background:colors[k]}}/><span>{k}</span><b>{n}</b><small>{fmt(n/Math.max(1,s.total_students)*100)}%</small></button>)}</div></div></Panel>
      <div id="signal-map"><Panel title="Score × attendance" subtitle="Each dot is a student · hover for evidence, click for Student 360"><svg className="data-svg" viewBox="0 0 520 250" role="img" aria-label="Scatter plot with score on horizontal axis and attendance on vertical axis"><rect x="40" y="20" width="270" height="185" fill="#ef776b" opacity=".07"/>{[0,25,50,75,100].map(v=><g key={v}><line x1="40" x2="490" y1={205-v*1.85} y2={205-v*1.85} className="grid-line"/><text x="5" y={209-v*1.85}>{v}</text><text x={40+v*4.5} y="224" textAnchor="middle">{v}</text></g>)}<line x1="310" x2="310" y1="20" y2="205" stroke="var(--coral)" strokeDasharray="4 5"/><line x1="40" x2="490" y1="66.25" y2="66.25" stroke="var(--amber)" strokeDasharray="4 5"/><text x="265" y="246" textAnchor="middle">Score %</text><text x="46" y="15">Attendance %</text>{rows.filter(r=>r.current_average!=null&&r.attendance!=null).map(r=><circle key={r.id} cx={40+r.current_average*4.5} cy={205-r.attendance*1.85} r={hover?.id===r.id?7:4} fill={colors[r.status]} opacity={hover&&hover.id!==r.id ? .25 : .7} className="svg-control" role="button" tabIndex="0" aria-label={`${r.name}, score ${r.current_average}, attendance ${r.attendance}, ${r.status}`} onMouseEnter={()=>setHover(r)} onMouseLeave={()=>setHover(null)} onFocus={()=>setHover(r)} onBlur={()=>setHover(null)} onClick={()=>onStudent(r.id)} onKeyDown={e=>{if(e.key==='Enter'){onStudent(r.id)}}}><title>{`${r.name} · ${r.status} · Score ${r.current_average}% · Attendance ${r.attendance}%`}</title></circle>)}</svg><div className="chart-tooltip" aria-live="polite">{hover?<><b>{hover.name} · {hover.status}</b><span>Score {fmt(hover.current_average)}% · Attendance {fmt(hover.attendance)}% · Change {fmt(hover.trend_delta)} points</span></>:<><b>Look for low scores and low attendance</b><span>Dashed guides: score 60% and attendance 75%. Open a dot to review its evidence.</span></>}</div></Panel></div>
      <div id="score-bands"><Panel title="Score distribution" subtitle="Student counts · missing scores excluded"><div className="histogram">{bands.map((b,i)=><div className="hist-column" key={b.label}><b>{b.n}</b><div className="hist-track"><div style={{height:`${b.n/Math.max(1,...bands.map(b=>b.n))*100}%`,background:i===0?colors['At Risk']:i===1?colors['Slow Learner']:'var(--blue)'}}/></div><span>{b.label}</span></div>)}</div><p className="chart-foot">{rows.filter(r=>r.current_average==null).length} students with incomplete scores · scores use the selected term and subject.</p></Panel></div>
      <Panel title="Class comparison" subtitle="Percentage average · the selected student group" action={<div className="segmented">{['score','attendance'].map(k=><button key={k} className={metric===k?'selected':''} aria-pressed={metric===k} onClick={()=>setMetric(k)}>{k==='score'?'Score':'Attendance'}</button>)}</div>}><div className="horizontal-bars">{classes.map(c=><div key={c.name}><span>{c.name}<small>{c.n} students</small></span><div className="bar-track"><div style={{width:`${c.value??0}%`,background:metric==='score'?'var(--blue)':'var(--mint)'}}/></div><b>{fmt(c.value)}%</b></div>)}</div>{!classes.length&&<p className="sub">No students in this selection.</p>}</Panel>
      <Panel title="Why students were flagged" subtitle="Counts can overlap: one student may have several signals"><div className="horizontal-bars">{signals.slice(0,6).map(x=><div key={x.k}><span>{reasons[x.k]}</span><div className="bar-track"><div style={{width:`${x.n/Math.max(1,rows.length)*100}%`,background:'var(--lav)'}}/></div><b>{x.n}</b></div>)}</div>{!signals.length&&<p className="sub">No review signals in this group.</p>}<button className="text-button" onClick={()=>setExplain(!explain)}>Explore the backend rules →</button></Panel>
    </div>
    <Panel title="Student review queue" subtitle={`${queue.length} matches · ${status==='All'?'all categories':status} · click a student to inspect academic and support history`} action={<button className="btn secondary" onClick={()=>onPage('support')}>Arrange support →</button>}><div className="queue-controls"><input value={search} onChange={e=>setSearch(e.target.value)} aria-label="Search review queue" placeholder="Search student name…"/><select aria-label="Sort review queue" value={sort} onChange={e=>setSort(e.target.value)}><option value="priority">Review priority</option><option value="score">Lowest score first</option><option value="decline">Largest decline first</option></select></div><div className="table-wrap"><table><thead><tr>{['Student','Status','Score','Attendance','Change','Evidence','Review'].map(k=><th key={k}>{k}</th>)}</tr></thead><tbody>{queue.slice(0,20).map(r=><tr key={r.id}><td><b>{r.name}</b><small className="cell-sub">{r.class_name}</small></td><td><span className="status-label" style={{color:colors[r.status]}}><i style={{background:colors[r.status]}}/>{r.status}</span></td><td>{fmt(r.current_average)}%</td><td>{fmt(r.attendance)}%</td><td className={r.trend_delta<0?'negative':''}>{r.trend_delta>0?'+':''}{fmt(r.trend_delta)} pts</td><td>{(r.reason_codes||[]).map(k=>reasons[k]||k).join(' · ')}</td><td><button className="btn secondary" onClick={()=>onStudent(r.id)}>Open ↗</button></td></tr>)}</tbody></table></div>{!queue.length&&<p className="sub">No students match this selection.</p>}<p className="chart-foot">Showing up to 20 students. Download visible data includes all {rows.length} students in the selected group.</p></Panel>
    <div className="callout">Live database reads every 10 seconds while this page is visible. The Power BI Web connector imports these records when its model refreshes. Support comparisons describe progress; they do not establish the cause of a change.</div>
  </>;
}
if(typeof document!=='undefined'){
  const root=createRoot(document.getElementById('react-dashboard'));
  window.renderDashboard=props=>root.render(<Dashboard {...props}/>);
}
